### ISSUE TITLE
BUG: Not using environmental variable for enabled in the runtime

### ISSUE THREAD

**Issue by ErayGjg** [neptune-ai/kedro-neptune#37]
### Describe the bug

In the example project template there is a config named enabled as an environmental variable but it does not support environmental variables in the run time.

### Reproduction

kedro neptune init will add following config in the base config
`
enabled: $NEPTUNE_ENABLED
`

exporting relevant enviroment variable

`
export NEPTUNE_ENABLED=false
`
Could be solved with: https://github.com/neptune-ai/kedro-neptune/pull/35

### Expected behavior

No metrics will be passed to Neptune

### Environment

**The operating system you're using: Mac OS
**The output of `python --version`: python 3.9

**Comment by Blaizzy** [comment]
Hi,

Prince Canuma here, a Data Scientist at Neptune.ai,

I'm really sorry for the late reply.

Thank you for your patience and the feedback! We are always looking for ways to improve our services.

I'm glad you shared the solution too, I have notified the devs to review and that PR.

Meanwhile, I would like to ask what is your use case for you to want to disable Neptune tracking using an env variable? This will help me better understand and explain to the product team the use case for env variables support.

**Comment by Blaizzy** [comment]
Hi @ErayGjg 

I'm just checking back to see if you still need help with this issue? or if you have any other questions I can help you with?

**Comment by ErayGjg** [comment]
Hi @Blaizzy 
We still want to control whenever the neptune wıll be enabled or not via environmental variables rather than using hard coded parameters.

**Comment by Blaizzy** [comment]
Great! We are working on that with a contributor.

You can follow the progress in this PR: https://github.com/neptune-ai/kedro-neptune/pull/35

**Comment by Blaizzy** [comment]
Let me know if this solves your issue!
