### ISSUE TITLE
BUG: TypeError: run must be a Run (was <class 'neptune.new.handler.Handler'>) when running with optuna

### ISSUE THREAD

**Issue by bethrice44** [neptune-ai/kedro-neptune#46]
### Describe the bug

- Running with `optuna` with neptune raises a `TypeError` due to the fact that the `neptune_run` object is of type `neptune.new.handler.Handler` not `Run`. 

### Reproduction
```
def train_model(df_train, y_label, features, neptune_run:  neptune.handler.Handler):
    X_train = df_train[features].values
    y_train = df_train[y_label].values

    def objective(trial):
        n_estimators = trial.suggest_int('n_estimators', 2, 50)
        max_depth = int(trial.suggest_loguniform('max_depth', 1, 20))
        model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)
        return cross_val_score(model, X_train, y_train, 
            n_jobs=-1, cv=5).mean()

    study = optuna.create_study(direction='maximize')
    neptune_callback = optuna_utils.NeptuneCallback(neptune_run)
```

### Expected behavior
It should be possible to get the `run` object from the `neptune_run` handler to pass to `NeptuneCallback`.

Issue also raised in `neptune-optuna` [here](https://github.com/neptune-ai/neptune-optuna/issues/12) and one suggestion doesn't use the `kedro` integration, while the other says use `neptune.run.Handler`, but this is coded into the `kedro` integration. 

### Traceback
```
│ ❱ 165 │   │   neptune_callback = optuna_utils.NeptuneCallback(neptune_run)                       │
│ ❱ 118 │   │   verify_type('run', run, neptune.Run)                                               │
│    44 │   if not isinstance(var, expected_type):                                                 │
│ ❱  45 │   │   raise TypeError("{} must be a {} (was {})".format(var_name, type_name, type(var    │

TypeError: run must be a Run (was <class 'neptune.new.handler.Handler'>)

```

**Comment by Blaizzy** [comment]
Hi @bethrice44 

Thanks for reporting,

Do you mind sharing what version of neptune-client you are using?

**Comment by Blaizzy** [comment]
In your case, you are using 2 integrations at once and both take different types.

Trying to replicate your issue to see the possible solutions, and I will come back to you as soon as possible.

**Comment by bethrice44** [comment]
Thanks for your quick reply. I'm using version `0.1.3` and you are correct that the two integrations don't agree on type. I was wondering if there is a way to extract a `Run` object from a `Handler` object?

**Comment by Blaizzy** [comment]
Hi @bethrice44 

I have replicated your issue and found a solution.

You can extract a `Run` object from a `Handler` object using the `container` property.

Example:
```
def train_model(df_train, y_label, features, neptune_run:  neptune.handler.Handler):
    X_train = df_train[features].values
    y_train = df_train[y_label].values

    def objective(trial):
        n_estimators = trial.suggest_int('n_estimators', 2, 50)
        max_depth = int(trial.suggest_loguniform('max_depth', 1, 20))
        model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)
        return cross_val_score(model, X_train, y_train, 
            n_jobs=-1, cv=5).mean()

    study = optuna.create_study(direction='maximize')
    neptune_callback = optuna_utils.NeptuneCallback(neptune_run.container)
```

We have an example here:
https://github.com/neptune-ai/kedro-neptune/blob/main/examples/planets/src/planets/pipelines/moons_classifier.py#L97

Let me know if this helps you,

**Comment by bethrice44** [comment]
Thats great - thank you so much 🙂

**Comment by Blaizzy** [comment]
No problem at all 😊 

Feel free to reach out should come across any further questions or concerns.
