### ISSUE TITLE
Feature Request: Allow `neptune_run` `custom_run_id` to be overwritten

### ISSUE THREAD

**Issue by bethrice44** [neptune-ai/kedro-neptune#47]
### Is your feature request related to a problem? Please describe.

I am trying to use neptune<>optuna<>kedro to [log each optuna trial as a separate neptune run](https://docs.neptune.ai/integrations-and-supported-tools/hyperparameter-optimization/optuna#log-each-trial-as-a-separate-neptune-run), as described in the linked tutorial. 

However, I have found that the suggested code only works if I set 
```
  enabled: false
```

in `neptune_config.yml` created by `kedro-neptune`. 

I believe this is because `NEPTUNE_CUSTOM_RUN_ID` is set as [an environment variable](https://github.com/neptune-ai/kedro-neptune/blob/bfe4da4c55e15a82f2453cb5f1eeb065e8c008ea/kedro_neptune/__init__.py#L412), which overwrites any default `run_id` created for a new `neptune.init()`.

### Describe the solution you'd like

A way to overwrite the `custom_run_id` when `kedro-neptune` is running, maybe a parameter in `neptune.yml` to say `set_custom_run_id_env_variable` as true or false.

### Describe alternatives you've considered

My current workaround is to set `enabled: false` to essentially "turn off" the integration with `kedro` to ensure the `optuna` one works as expected.

**Comment by Blaizzy** [comment]
Hi @bethrice44 

Great question!

You can do that in your code

Example:

```python
# nodes.py
def report_accuracy(y_pred: pd.Series, y_test: pd.Series, neptune_run: neptune.Run):
    accuracy = ...
    neptune_run["nodes/report/accuracy"] = accuracy * 100

    fig, ax = ...
    neptune_run["nodes/report/confusion_matrix"].upload(fig)

    for i in range(2):
            # create new run by overloading `custom_run_id`
            custom_run_id = f"test_{i}"
            run_trial_level = neptune.init_run(tags=["optuna_trial"], custom_run_id=custom_run_id)
            ...
            # log score of a trial-level Run
            run_trial_level['score'] = score

```

The code above will create 3 runs. The first will be the `kedro run`, and the last two will be `optuna runs`.

Docs: https://docs.neptune.ai/api-reference/neptune#.init_run

Let me know if this works for you

**Comment by bethrice44** [comment]
Hey, thanks for your reply. 

Yes that seems to work - thank you! I think my issue before was trying to set the `study_level` run with the `neptune_run` kedro object rather that its own thing.

**Comment by Blaizzy** [comment]
Perfect!

Now to answer your question:
I think it depends on your preference.

- You can have both study level and kedro metadata in the same run.
- You can have both study level and kedro metadata in separate runs.
- You can have study level and trial level in separate runs
- You can have just study-level metadata and so on. 

We give you the freedom to choose what setup/structure best works for you and facilitate your understanding, comparison, and analysis of the metadata you logged.

**Comment by Blaizzy** [comment]
Feel free to reach out if you come across any other issues or questions,
I'm happy to help.
