### ISSUE TITLE
BUG: KeyError: "No config patterns were found for 'credentials_neptune' in your config loader"

### ISSUE THREAD

**Issue by Muhammed-Rashid-07** [neptune-ai/kedro-neptune#78]
### Describe the bug
I am using neptune with kedro. When I try to run kedro neptune init. I got this error. I have stored api_token and project name in the .env which is in the root directory.

When I installed kedro-neptune there is no file like neptune.yml and neptune_credentials.yml in the conf folder

ERROR:
rashid@Muhammeds-MacBook-Air sales-project2 % kedro neptune init
Pass a Neptune API token or press enter if you want to use the $NEPTUNE_API_TOKEN environment variable: [$NEPTUNE_API_TOKEN]: 
Pass a Neptune project name in the form 'workspace/project' or press enter if you want to use the $NEPTUNE_PROJECT environment variable: [$NEPTUNE_PROJECT]: 
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Applications/anaconda3/envs/sales-project/bin/kedro:8 in <module>                               │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/framework/cli/cli. │
│ py:211 in main                                                                                   │
│                                                                                                  │
│   208 │   """                                                                                    │
│   209 │   _init_plugins()                                                                        │
│   210 │   cli_collection = KedroCLI(project_path=Path.cwd())                                     │
│ ❱ 211 │   cli_collection()                                                                       │
│   212                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:1157 in    │
│ __call__                                                                                         │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/framework/cli/cli. │
│ py:139 in main                                                                                   │
│                                                                                                  │
│   136 │   │   )                                                                                  │
│   137 │   │                                                                                      │
│   138 │   │   try:                                                                               │
│ ❱ 139 │   │   │   super().main(                                                                  │
│   140 │   │   │   │   args=args,                                                                 │
│   141 │   │   │   │   prog_name=prog_name,                                                       │
│   142 │   │   │   │   complete_var=complete_var,                                                 │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:1078 in    │
│ main                                                                                             │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:1688 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:1688 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:1434 in    │
│ invoke                                                                                           │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/core.py:783 in     │
│ invoke                                                                                           │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/click/decorators.py:45   │
│ in new_func                                                                                      │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro_neptune/__init__.p │
│ y:177 in init                                                                                    │
│                                                                                                  │
│   174 │   │   https://docs.neptune.ai/integrations/kedro/                                        │
│   175 │   """                                                                                    │
│   176 │   session = KedroSession(metadata.package_name)                                          │
│ ❱ 177 │   context = session.load_context()                                                       │
│   178 │                                                                                          │
│   179 │   yaml = YAML()                                                                          │
│   180 │   context.credentials_file = context.project_path / settings.CONF_SOURCE / "local" / "   │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/framework/session/ │
│ session.py:284 in load_context                                                                   │
│                                                                                                  │
│   281 │   │   │   extra_params=extra_params,                                                     │
│   282 │   │   │   hook_manager=self._hook_manager,                                               │
│   283 │   │   )                                                                                  │
│ ❱ 284 │   │   self._hook_manager.hook.after_context_created(context=context)                     │
│   285 │   │                                                                                      │
│   286 │   │   return context                                                                     │
│   287                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_hooks.py:433 in  │
│ __call__                                                                                         │
│                                                                                                  │
│   430 │   │   ), "Cannot directly call a historic hook - use call_historic instead."             │
│   431 │   │   self._verify_all_args_are_provided(kwargs)                                         │
│   432 │   │   firstresult = self.spec.opts.get("firstresult", False) if self.spec else False     │
│ ❱ 433 │   │   return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)             │
│   434 │                                                                                          │
│   435 │   def call_historic(                                                                     │
│   436 │   │   self,                                                                              │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:112   │
│ in _hookexec                                                                                     │
│                                                                                                  │
│   109 │   ) -> object | list[object]:                                                            │
│   110 │   │   # called from all hookcaller instances.                                            │
│   111 │   │   # enable_tracing will set its own wrapping function at self._inner_hookexec        │
│ ❱ 112 │   │   return self._inner_hookexec(hook_name, methods, kwargs, firstresult)               │
│   113 │                                                                                          │
│   114 │   def register(self, plugin: _Plugin, name: str | None = None) -> str | None:            │
│   115 │   │   """Register a plugin and return its name.                                          │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:418   │
│ in traced_hookexec                                                                               │
│                                                                                                  │
│   415 │   │   │   │   lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)         │
│   416 │   │   │   )                                                                              │
│   417 │   │   │   after(outcome, hook_name, hook_impls, caller_kwargs)                           │
│ ❱ 418 │   │   │   return outcome.get_result()                                                    │
│   419 │   │                                                                                      │
│   420 │   │   self._inner_hookexec = traced_hookexec                                             │
│   421                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_result.py:108 in │
│ get_result                                                                                       │
│                                                                                                  │
│   105 │   │   if exc is None:                                                                    │
│   106 │   │   │   return cast(_T, self._result)                                                  │
│   107 │   │   else:                                                                              │
│ ❱ 108 │   │   │   raise exc.with_traceback(exc.__traceback__)                                    │
│   109                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_result.py:70 in  │
│ from_call                                                                                        │
│                                                                                                  │
│    67 │   │   __tracebackhide__ = True                                                           │
│    68 │   │   result = exception = None                                                          │
│    69 │   │   try:                                                                               │
│ ❱  70 │   │   │   result = func()                                                                │
│    71 │   │   except BaseException as exc:                                                       │
│    72 │   │   │   exception = exc                                                                │
│    73 │   │   return cls(result, exception)                                                      │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:415   │
│ in <lambda>                                                                                      │
│                                                                                                  │
│   412 │   │   ) -> object | list[object]:                                                        │
│   413 │   │   │   before(hook_name, hook_impls, caller_kwargs)                                   │
│   414 │   │   │   outcome = _Result.from_call(                                                   │
│ ❱ 415 │   │   │   │   lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)         │
│   416 │   │   │   )                                                                              │
│   417 │   │   │   after(outcome, hook_name, hook_impls, caller_kwargs)                           │
│   418 │   │   │   return outcome.get_result()                                                    │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_callers.py:116   │
│ in _multicall                                                                                    │
│                                                                                                  │
│   113 │   │   │   │   _raise_wrapfail(teardown, "has second yield")  # type: ignore[arg-type]    │
│   114 │   │   │                                                                                  │
│   115 │   │   │   if exception is not None:                                                      │
│ ❱ 116 │   │   │   │   raise exception.with_traceback(exception.__traceback__)                    │
│   117 │   │   │   else:                                                                          │
│   118 │   │   │   │   return result                                                              │
│   119                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_callers.py:80 in │
│ _multicall                                                                                       │
│                                                                                                  │
│    77 │   │   │   │   │   except StopIteration:                                                  │
│    78 │   │   │   │   │   │   _raise_wrapfail(function_gen, "did not yield")                     │
│    79 │   │   │   │   else:                                                                      │
│ ❱  80 │   │   │   │   │   res = hook_impl.function(*args)                                        │
│    81 │   │   │   │   │   if res is not None:                                                    │
│    82 │   │   │   │   │   │   results.append(res)                                                │
│    83 │   │   │   │   │   │   if firstresult:  # halt further impl calls                         │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro_telemetry/plugin.p │
│ y:128 in after_context_created                                                                   │
│                                                                                                  │
│   125 │   │                                                                                      │
│   126 │   │   logger.debug("You have opted into product usage analytics.")                       │
│   127 │   │                                                                                      │
│ ❱ 128 │   │   catalog = context.catalog                                                          │
│   129 │   │   default_pipeline = pipelines.get("__default__")  # __default__                     │
│   130 │   │   hashed_username = _get_hashed_username()                                           │
│   131                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/framework/context/ │
│ context.py:226 in catalog                                                                        │
│                                                                                                  │
│   223 │   │   │   KedroContextError: Incorrect ``DataCatalog`` registered for the project.       │
│   224 │   │                                                                                      │
│   225 │   │   """                                                                                │
│ ❱ 226 │   │   return self._get_catalog()                                                         │
│   227 │                                                                                          │
│   228 │   @property                                                                              │
│   229 │   def params(self) -> dict[str, Any]:                                                    │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/framework/context/ │
│ context.py:287 in _get_catalog                                                                   │
│                                                                                                  │
│   284 │   │   feed_dict = self._get_feed_dict()                                                  │
│   285 │   │   catalog.add_feed_dict(feed_dict)                                                   │
│   286 │   │   _validate_transcoded_datasets(catalog)                                             │
│ ❱ 287 │   │   self._hook_manager.hook.after_catalog_created(                                     │
│   288 │   │   │   catalog=catalog,                                                               │
│   289 │   │   │   conf_catalog=conf_catalog,                                                     │
│   290 │   │   │   conf_creds=conf_creds,                                                         │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_hooks.py:433 in  │
│ __call__                                                                                         │
│                                                                                                  │
│   430 │   │   ), "Cannot directly call a historic hook - use call_historic instead."             │
│   431 │   │   self._verify_all_args_are_provided(kwargs)                                         │
│   432 │   │   firstresult = self.spec.opts.get("firstresult", False) if self.spec else False     │
│ ❱ 433 │   │   return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)             │
│   434 │                                                                                          │
│   435 │   def call_historic(                                                                     │
│   436 │   │   self,                                                                              │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:112   │
│ in _hookexec                                                                                     │
│                                                                                                  │
│   109 │   ) -> object | list[object]:                                                            │
│   110 │   │   # called from all hookcaller instances.                                            │
│   111 │   │   # enable_tracing will set its own wrapping function at self._inner_hookexec        │
│ ❱ 112 │   │   return self._inner_hookexec(hook_name, methods, kwargs, firstresult)               │
│   113 │                                                                                          │
│   114 │   def register(self, plugin: _Plugin, name: str | None = None) -> str | None:            │
│   115 │   │   """Register a plugin and return its name.                                          │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:418   │
│ in traced_hookexec                                                                               │
│                                                                                                  │
│   415 │   │   │   │   lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)         │
│   416 │   │   │   )                                                                              │
│   417 │   │   │   after(outcome, hook_name, hook_impls, caller_kwargs)                           │
│ ❱ 418 │   │   │   return outcome.get_result()                                                    │
│   419 │   │                                                                                      │
│   420 │   │   self._inner_hookexec = traced_hookexec                                             │
│   421                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_result.py:108 in │
│ get_result                                                                                       │
│                                                                                                  │
│   105 │   │   if exc is None:                                                                    │
│   106 │   │   │   return cast(_T, self._result)                                                  │
│   107 │   │   else:                                                                              │
│ ❱ 108 │   │   │   raise exc.with_traceback(exc.__traceback__)                                    │
│   109                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_result.py:70 in  │
│ from_call                                                                                        │
│                                                                                                  │
│    67 │   │   __tracebackhide__ = True                                                           │
│    68 │   │   result = exception = None                                                          │
│    69 │   │   try:                                                                               │
│ ❱  70 │   │   │   result = func()                                                                │
│    71 │   │   except BaseException as exc:                                                       │
│    72 │   │   │   exception = exc                                                                │
│    73 │   │   return cls(result, exception)                                                      │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_manager.py:415   │
│ in <lambda>                                                                                      │
│                                                                                                  │
│   412 │   │   ) -> object | list[object]:                                                        │
│   413 │   │   │   before(hook_name, hook_impls, caller_kwargs)                                   │
│   414 │   │   │   outcome = _Result.from_call(                                                   │
│ ❱ 415 │   │   │   │   lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)         │
│   416 │   │   │   )                                                                              │
│   417 │   │   │   after(outcome, hook_name, hook_impls, caller_kwargs)                           │
│   418 │   │   │   return outcome.get_result()                                                    │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_callers.py:116   │
│ in _multicall                                                                                    │
│                                                                                                  │
│   113 │   │   │   │   _raise_wrapfail(teardown, "has second yield")  # type: ignore[arg-type]    │
│   114 │   │   │                                                                                  │
│   115 │   │   │   if exception is not None:                                                      │
│ ❱ 116 │   │   │   │   raise exception.with_traceback(exception.__traceback__)                    │
│   117 │   │   │   else:                                                                          │
│   118 │   │   │   │   return result                                                              │
│   119                                                                                            │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/pluggy/_callers.py:80 in │
│ _multicall                                                                                       │
│                                                                                                  │
│    77 │   │   │   │   │   except StopIteration:                                                  │
│    78 │   │   │   │   │   │   _raise_wrapfail(function_gen, "did not yield")                     │
│    79 │   │   │   │   else:                                                                      │
│ ❱  80 │   │   │   │   │   res = hook_impl.function(*args)                                        │
│    81 │   │   │   │   │   if res is not None:                                                    │
│    82 │   │   │   │   │   │   results.append(res)                                                │
│    83 │   │   │   │   │   │   if firstresult:  # halt further impl calls                         │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro_neptune/__init__.p │
│ y:425 in after_catalog_created                                                                   │
│                                                                                                  │
│   422 │   def after_catalog_created(self, catalog: DataCatalog) -> None:                         │
│   423 │   │   self._run_id = hashlib.md5(str(time.time()).encode()).hexdigest()                  │
│   424 │   │                                                                                      │
│ ❱ 425 │   │   config = get_neptune_config(settings)                                              │
│   426 │   │                                                                                      │
│   427 │   │   if config.enabled:                                                                 │
│   428 │   │   │   os.environ["NEPTUNE_CUSTOM_RUN_ID"] = self._run_id                             │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro_neptune/config.py: │
│ 36 in get_neptune_config                                                                         │
│                                                                                                  │
│   33                                                                                             │
│   34 def get_neptune_config(settings) -> NeptuneConfig:                                          │
│   35 │   config_loader = settings.CONFIG_LOADER_CLASS(settings.CONF_SOURCE, **settings.CONFIG    │
│ ❱ 36 │   credentials = config_loader["credentials_neptune"]                                      │
│   37 │   config = config_loader["neptune"]                                                       │
│   38 │                                                                                           │
│   39 │   api_token = parse_config_value(credentials["neptune"]["api_token"])                     │
│                                                                                                  │
│ /Applications/anaconda3/envs/sales-project/lib/python3.10/site-packages/kedro/config/omegaconf_c │
│ onfig.py:182 in __getitem__                                                                      │
│                                                                                                  │
│   179 │   │   │   return super().__getitem__(key)                                                │
│   180 │   │                                                                                      │
│   181 │   │   if key not in self.config_patterns:                                                │
│ ❱ 182 │   │   │   raise KeyError(                                                                │
│   183 │   │   │   │   f"No config patterns were found for '{key}' in your config loader"         │
│   184 │   │   │   )                                                                              │
│   185 │   │   patterns = [*self.config_patterns[key]]                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: "No config patterns were found for 'credentials_neptune' in your config loader"

My virtual environment: conda
python version = 3.10
kedro version = 0.18.14
neptune ai =1.8.6

**Comment by SiddhantSadangi** [comment]
Hey @Muhammed-Rashid-07 👋 

I am not able to reproduce this error. The *neptune.yml files will be created in the conf folder only after running `kedro neptune init`. The error you have mentioned is generally encountered if you run `kedro run` without adding the config patterns needed to load the Neptune config to your project's `CONFIG_LOADER_ARGS` in the project's `settings.py`.

Could you try adding the below to `settings.py` and try running the project again?
```yml
CONFIG_LOADER_ARGS = {
    ...,
    "config_patterns": {
        ...,
        "credentials_neptune" : ["credentials_neptune*"],
        "neptune": ["neptune*"],
    }
}
```

**Comment by SiddhantSadangi** [comment]
Hey @Muhammed-Rashid-07 ,
I am closing this thread due to inactivity, but please feel free to open this if you are still facing this issue.
